apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  namespace: website
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    - website.bijubayarea.tk
    secretName: website-tls

  rules:
  - host: website.bijubayarea.tk
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: web-service
              port:
                number: 80
